/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class function_gpio_GPIO_Core_Jni */

#ifndef _Included_function_gpio_GPIO_Core_Jni
#	define _Included_function_gpio_GPIO_Core_Jni
#	ifdef __cplusplus
extern "C" {
#	endif
/*
 * Class:     function_gpio_GPIO_Core_Jni
 * Method:    env_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_function_gpio_GPIO_1Core_00024Jni_env_1init(JNIEnv*, jclass);

/*
 * Class:     function_gpio_GPIO_Core_Jni
 * Method:    pin_init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_function_gpio_GPIO_1Core_00024Jni_pin_1init(JNIEnv*, jclass, jint, jint);

/*
 * Class:     function_gpio_GPIO_Core_Jni
 * Method:    pin_read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_function_gpio_GPIO_1Core_00024Jni_pin_1read(JNIEnv*, jclass, jint);

/*
 * Class:     function_gpio_GPIO_Core_Jni
 * Method:    pin_write
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_function_gpio_GPIO_1Core_00024Jni_pin_1write(JNIEnv*, jclass, jint, jint);

#	ifdef __cplusplus
}
#	endif
#endif
